//@version=5
indicator("Auto Fibonacci Golden Pocket GP", shorttitle="Auto Fib GP", overlay=true, max_labels_count=500)
len = input.int(title="Pivot Length", defval=50, minval=1, inline="Pivot Length", group='Fibonacci Settings')
showInverted = input.bool(false, title = 'Show Inverted', group='Fibonacci Settings')
showZeroAndHalf = input.bool(false, title = 'Show 0.5 level', group='Fibonacci Settings')

drawPivotLabels = input.bool(true, title = 'Draw pivot point labels', group='Other')
ph = ta.pivothigh(len, len)
pl = ta.pivotlow(len, len)
drawLabel(_offset, _pivot, _style, _color, _textColor) =>
    if not na(_pivot) and drawPivotLabels
        label.new(bar_index[_offset], _pivot, str.tostring(_pivot, format.mintick), style=_style, color=_color, textcolor=_textColor, size = size.small)
drawLabel(len, ph, label.style_label_down, color.black, color.white)
drawLabel(len, pl, label.style_label_up, color.black, color.white)
var float lastPh = na
var float lowestFromLastPh = na
var float lastPl = na
var float highestFromLastPl = na
if (na(lastPh) or lastPh != ph) and not na(ph)
    lowestFromLastPh := low
    lastPh := ph
if (na(lastPl) or lastPl != pl) and not na(pl)
    lastPl := pl
    highestFromLastPl := high
if high > highestFromLastPl
    highestFromLastPl := high
if low < lowestFromLastPh
    lowestFromLastPh := low
p1 = plot(highestFromLastPl - (highestFromLastPl - lastPl) * 0.618, color = color.yellow, style= plot.style_line, title = 'GP 0.618')
p2 = plot(highestFromLastPl - (highestFromLastPl - lastPl) * 0.65, color = color.yellow, style= plot.style_line, title = 'GP 0.65')
p5 = plot(showZeroAndHalf ? highestFromLastPl - (highestFromLastPl - lastPl) * 0.5 : na, color = color.green, style= plot.style_line, title = 'GP 0.5')
fill(p1, p2, color.rgb(72, 255, 59, 90))
fill(p2, p5, showZeroAndHalf ? color.rgb(72, 255, 59, 96) : na)

p3 = plot(showInverted ? lowestFromLastPh + (lastPh - lowestFromLastPh) * 0.618 : na, color = color.yellow, style= plot.style_line, title = 'GP 0.618 (inverted)')
p4 = plot(showInverted ? lowestFromLastPh + (lastPh - lowestFromLastPh) * 0.65 : na, color = color.yellow, style= plot.style_line, title = 'GP 0.65 (inverted)')
p6 = plot(showInverted and showZeroAndHalf ? lowestFromLastPh + (lastPh - lowestFromLastPh) * 0.5 : na, color = color.green, style= plot.style_line, title = 'GP 0.5 (inverted)')
fill(p3, p4, showInverted ? color.rgb(255, 59, 59, 90) : na)
fill(p3, p6, showInverted and showZeroAndHalf ? color.rgb(255, 59, 59, 96) : na)

